import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import { Box, Container, useTheme } from "@mui/material"
import Footer from './../components/Footer';
import HeroSection from '@/components/HeroSection'
import OurServices from '@/components/OurServices'
import BookRideSection from '@/components/BookRideSection'
import ServiceProviderSection from '@/components/ServiceProviderSection'
import DownloadAppSection from '@/components/DownloadAppSection'
import ContactForm from '@/components/ContactForm'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const theme = useTheme()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ padding: "0px 50px" }}>
        <Header />
      </Box>

      <Container
        //@ts-ignore
        maxWidth={"xl"}
        sx={{ justifyContent: "center", width: "100%", display: "flex", flexDirection: "column", gap: "120px", marginBottom: "50px" }}
      >
        <Box>
          <HeroSection />
        </Box>
        <OurServices />
        <BookRideSection />
        <ServiceProviderSection />
        <Box sx={{ position: "relative" }}>
          <Box sx={{ position: "absolute", backgroundColor: `${theme.palette.primary.main}`, borderRadius: "50%", left: -610, }}>
            <Image src={"/images/Face 2@2x.png"} width={928} height={928} alt={"Iphone App"} />
          </Box>
          <DownloadAppSection />
        </Box>
        <ContactForm />
      </Container>
      <Footer />
    </>
  )
}
